apiVersion: v1
kind: Pod
metadata:
  name: mysql-db
  namespace: corso
  labels:
    app: mysql-db
spec:
  containers:
  - name: mysql-db
    image: mysql:5.6
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "Password123"
    ports:
    - containerPort: 3306
      protocol: TCP
  restartPolicy: Always
