apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: corso
  labels:
    app: web-app-service
spec:
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 3000        # Porta del service  (interna al cluster)
    targetPort: 3000  # Porta del container 
    nodePort: 30080   # Porta esposta sui nodi del cluster (per accesso esterno) (range 30000-32767)
  type: NodePort